# Generated by Django 3.2.9 on 2021-12-04 19:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.IntegerField()),
                ('lat', models.FloatField(blank=True, default=0.0, null=True)),
                ('lon', models.FloatField(blank=True, default=0.0, null=True)),
                ('country_long', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('route', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sub_locality_level_1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sub_locality_level_2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sub_locality_level_3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sub_locality_level_4', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sub_locality_level_5', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('administrative_area_level_1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('administrative_area_level_2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('administrative_area_level_3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('administrative_area_level_4', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('administrative_area_level_5', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('locality', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('property_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('searchable_status', models.BooleanField(default=True)),
                ('verification_status', models.BooleanField(default=True)),
                ('administration_status', models.BooleanField(default=True)),
                ('property_purpose', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('property_long_description', models.TextField(default='No Description')),
                ('water_source', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('sewage_source', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('zoning', models.IntegerField(blank=True, null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=355, null=True), blank=True, null=True, size=None)),
                ('is_building', models.BooleanField(default=True)),
                ('has_blocks', models.BooleanField(default=True)),
                ('featured_status', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('area', models.FloatField(blank=True, default=0.0, null=True)),
                ('area_description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lowest_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('highest_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('single_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('negotiation', models.BooleanField(default=True)),
                ('is_pets_allowed', models.BooleanField(default=False)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('unit_count', models.IntegerField(blank=True, default=0, null=True)),
                ('property_type', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsersToRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.IntegerField()),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='name')),
                ('session_key', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInteractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view', models.BooleanField(default=False)),
                ('fav', models.BooleanField(default=False)),
                ('order', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendation_app.propertydetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendation_app.userstorecommend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationsToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendation_app.userstorecommend')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
