# Generated by Django 3.2.9 on 2021-12-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendation_app', '0002_alter_propertydetails_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorecommend',
            name='item_id',
            field=models.IntegerField(unique=True),
        ),
    ]
